export const LOGIN_ROUTE = '/login';
export const WEATHER_MAP_ROUTE = '/map';

export const FETCH_GOOGLE_USER = 'FETCH_GOOGLE_USER';
export const FETCH_GOOGLE_USER_SUCCESS = 'FETCH_GOOGLE_USER_SUCCESS';
export const FETCH_GOOGLE_USER_ERROR = 'FETCH_GOOGLE_USER_ERROR';
export const FETCH_GOOGLE_AUTH_OBJ = 'FETCH_GOOGLE_AUTH_OBJ';

export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
export const CLEAR_WEATHER_DATA = 'CLEAR_WEATHER_DATA';

export const ADD_FORECAST_REQUEST = 'ADD_FORECAST_REQUEST';
export const DELETE_FORECAST_REQUEST = 'DELETE_FORECAST_REQUEST';